
server (re)started
Traceback (most recent call last):
  File "/var/www/html/ssch/python/server.py", line 333, in service
    makeFile(
  File "/var/www/html/ssch/python/makeXl.py", line 55, in makeFile
    d1, d2 = divider(data, height)
  File "/var/www/html/ssch/python/makeXl.py", line 14, in divider
    data.extend([copy(form) for _ in range(46 - len(data))])
AttributeError: 'tuple' object has no attribute 'extend'
